[tool.poetry]
name = "vectara-inference-api"
version = "0.1.0"
description = "Flask API for Vectara model inference"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
torch = { url = "https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.2.2%2Bcpu.cxx11.abi-cp38-cp38-linux_x86_64.whl#sha256=fe0d4d0082f684cd7ef6592a0324ffafce6017925f3fdf10165abe5e89458d82", markers = "platform_machine == 'x86_64' and platform_python_implementation == 'CPython' and platform_system == 'Linux'" }
flask = "^3.0.3"
transformers = "^4.44.0"
peft = "0.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"