[tool.poetry]
name = "vectara-inference-api"
version = "0.1.0"
description = "Flask API for Vectara model inference"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.4.0"
flask = "^3.0.3"
transformers = "^4.44.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"